// ROTA LIVROS
GET http://localhost:8080/livros
###
GET http://localhost:8080/livros/638251f1efd86b0b7da77719
###
POST http://localhost:8080/livros
Content-Type: application/json

{
    "TITULO": "Animais Normais",
    "AUTOR": "Sally Rooney, Débora Landsberg",
    "EDITORA": "63821b729544836bbbecdcd1",
    "PRECO": 20,
    "QUANTIDADE": 9
}
###
PUT http://localhost:8080/livros/6380b0049500efe731105ae9
Content-Type: application/json
{
    "TITULO": "Animais Diferentes"
}
###
DELETE http://localhost:8080/livros/63811ba98851538d7cc00d8b

// ROTAS EDITORA
###
GET http://localhost:8080/editoras
###
GET http://localhost:8080/editoras/63821b729544836bbbecdcd1
###
POST http://localhost:8080/editoras
Content-Type: application/json

{
    "NOME": "Rocco",
    "CNPJ": "9241/08"
}
// Sextante
// Grupo Companhia das Letras
// Rocco
###
PUT http://localhost:8080/editoras/6380c0107ae191c90b6cc20b
Content-Type: application/json

{
    "NOME": "Roooo",
    "CNPJ": "9219/02"
}
###
DELETE http://localhost:8080/editoras/6380c0517ae191c90b6cc20f

//ADM
###
GET  http://localhost:8080/adm/
###
POST http://localhost:8080/adm/cadastro
Content-Type: application/json

{
    "usuario":"henriaaaaaaaque",
    "senha":"12343452345345"
}

###
POST http://localhost:8080/adm/login
Content-Type: application/json

{
    "usuario":"henriaaaaaaaque",
    "senha":"12343452345345"
}